# Based on the starter workflow https://github.com/actions/starter-workflows/blob/main/pages/static.yml

# Simple workflow for deploying static content to GitHub Pages
name: Deploy slides to Github Pages

on:
  push:
    branches:
      - main

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build static slides
        run: npx reveal-md slides.md --static
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '_static'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
